<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-JG6ZZD3" failures="2" tests="9" name="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" time="52.446" errors="0" timestamp="2024-09-05T12:52:39 IST" skipped="2">
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="OrderHistoryTest" time="4.648"/>
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="InvalidLoginErrorValidation" time="5.703">
    <skipped/>
  </testcase> <!-- InvalidLoginErrorValidation -->
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="InvalidLoginErrorValidation" time="5.099">
    <failure message="expected [Incorrect email or password.] but found [Logged IN]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Logged IN]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.InvalidLoginErrorValidation(submitOrderCompleteParallelAndReport_Test.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- InvalidLoginErrorValidation -->
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="FailBlankLogin" time="4.642">
    <skipped/>
  </testcase> <!-- FailBlankLogin -->
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="BlankLogin" time="5.173"/>
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="LoginErrorValidation" time="4.749"/>
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="submitOrder" time="8.234"/>
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="submitOrder" time="8.971"/>
  <testcase classname="PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test" name="FailBlankLogin" time="5.227">
    <failure message="expected [*Email is required] but found [*Email required]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [*Email is required] but found [*Email required]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test.FailBlankLogin(submitOrderCompleteParallelAndReport_Test.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- FailBlankLogin -->
</testsuite> <!-- PracticeTest.SeleniumFramework.submitOrderCompleteParallelAndReport_Test -->
